Fix "Unknown version, custom build?" in /version
FukkitMC/TaterBukkit pull request #2
Opened 2020-05-31 09:52 UTC by IsaiahPatton

Add new /version command that will display versions behind info instead of "Unknown version, custom build?"

From https://github.com/fungus-soft/bukkit4fabric/commit/93a74a98a42364b8eefba12dffc21cf61b9349b2

2020-05-31 09:54 UTC, hYdos commented
just double checking, you are checking if it builds & runs first right?

2020-05-31 09:54 UTC, ramidzkh commented
We already have enough gradle cursedness, I'm not going to use yet another plugin. It'd be better if it read it from the fabric.mod.json

2020-05-31 14:29 UTC, Devan-Kerman commented
concerned_tater

2020-05-31 20:16 UTC, hYdos commented
something tells me this is going to be bike shead'ed

2020-05-31 20:18 UTC, CoolMineman commented
just hard code the version string smh

2020-05-31 20:31 UTC, hYdos commented
honestly that would be a good solution for now

2020-06-01 02:07 UTC, hYdos requested changes

2020-06-01 02:07 UTC, hYdos commented on .gitignore
> +# Version file (autogenerated by gradle)
shouldn't need comments in the gitignore

2020-06-01 02:07 UTC, hYdos commented on .gitignore
> +
random space also shouldn't exist

2020-06-01 02:08 UTC, jearmstrong21 commented on .gitignore
> +
> something tells me this is going to be bike shead'ed

prediction 100

2020-06-01 02:16 UTC, CoolMineman commented
@IsaiahPatton hydos says you have to fix the pr or he will send you an irritater

2020-06-01 02:17 UTC, hYdos commented
i just asked to fix the pr :concern:

2020-06-14 01:33 UTC, hYdos commented
im just going to commit stale on this. it can be reopened at a later time.

2020-06-14 01:33 UTC, closed without merging